### ISSUE TITLE
Error when decrypting data in Parquet file: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by travisnielsen** [Azure/microsoft-data-encryption-sdk#2]
When running the `FileEncryptionDecryption_ParquetFile` sample, I'm unable to decrypt a column that was previously encrypted. This is the error:

```bash
Exception has occurred: CLR/System.AggregateException
An unhandled exception of type 'System.AggregateException' occurred in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Microsoft.Data.Encryption.FileEncryption.FileEncryptionExtensions.Decrypt(IEnumerable source, EncryptionSettings settings)
   at Microsoft.Data.Encryption.FileEncryption.ColumnarCryptographer.DecryptColumn(FileEncryptionSettings writerColumnSettings, IColumn column)
   at Microsoft.Data.Encryption.FileEncryption.ColumnarCryptographer.TransformColumn(IColumn column, FileEncryptionSettings readerSettings, FileEncryptionSettings writerSettings)
   at Microsoft.Data.Encryption.FileEncryption.ColumnarCryptographer.<>c__DisplayClass9_0.<Transform>b__1(IColumn column)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass9_0.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
```

## Repo Steps

1) Run `FileEncryptionDecryption_ParquetFile` with a valid key referenced in AzureKeyVaultKeyPath. Use Randomized encryption on column index 3 (only)
2) Confirm data is successfully encrypted in `out1.parquet`
3) Modify `inputFile` on line 33 to `out1.parquet`
4) Create a dictionary to host `EncryptionKeyStoreProvider` and provide it to the `ParquetFileReader` instance. This is necessary to avoid a different exception that gets thrown.
![image](https://user-images.githubusercontent.com/3196834/110186235-37f3d000-7dda-11eb-8cb3-c55450bb56e5.png)
5) Modify the `FileEncryptionSettings` for index 3 to Plaintext
![image](https://user-images.githubusercontent.com/3196834/110186361-99b43a00-7dda-11eb-8709-f785d36d2ec9.png)
6) Error is thrown at `cryptographer.Transform();`
![image](https://user-images.githubusercontent.com/3196834/110186476-00395800-7ddb-11eb-9a9c-13e8bb46b912.png)

**Comment by Xtrimmer** [comment]
This has been fixed in the Microsoft.Data.Encryption.FileEncryption v0.2.0-pre package.
https://www.nuget.org/packages/Microsoft.Data.Encryption.FileEncryption/
